[package]
name = "caca"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dw3000 = "0.1.3"
rppal = { version = "0.13.1", features = ["hal"] }
embedded-hal = "0.2.6"
